/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLyPizza.View;


import QuanLyPizza.Class.TAIKHOAN;
import static QuanLyPizza.Connect.MyConnect.getConnection;
import static QuanLyPizza.DAO.TaiKhoanDAO.dnTK;
import static QuanLyPizza.DAO.TaiKhoanDAO.getAllTK;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HUU77
 */
public class DangNhap extends javax.swing.JFrame {

//    static final String url = "jdbc:mysql://localhost:3306/doanoop";
//    static final String user = "root";
//    static final String pass = "1234";


    public DangNhap() {
        initComponents();
        setLocationRelativeTo(null);
        getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textTK = new javax.swing.JTextField();
        textPW = new javax.swing.JPasswordField();
        jlbDN = new javax.swing.JLabel();
        jcbGhiNho = new javax.swing.JCheckBox();
        jlbReset = new javax.swing.JLabel();
        lbDK = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("VNI-Ariston", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HI PIZZA!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 430, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 90, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TAI KHOAN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, -1));

        textTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTKActionPerformed(evt);
            }
        });
        textTK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textTKKeyPressed(evt);
            }
        });
        jPanel1.add(textTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 210, 30));

        textPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPWActionPerformed(evt);
            }
        });
        jPanel1.add(textPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 210, 30));

        jlbDN.setBackground(new java.awt.Color(0, 0, 0));
        jlbDN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlbDN.setForeground(new java.awt.Color(255, 255, 255));
        jlbDN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDN.setText("ĐĂNG NHẬP");
        jlbDN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbDNMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbDNMouseReleased(evt);
            }
        });
        jPanel1.add(jlbDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 430, -1));

        jcbGhiNho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcbGhiNho.setForeground(new java.awt.Color(255, 255, 255));
        jcbGhiNho.setText("Ghi NHo");
        jPanel1.add(jcbGhiNho, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 90, -1));

        jlbReset.setBackground(new java.awt.Color(0, 0, 0));
        jlbReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbReset.setForeground(new java.awt.Color(255, 255, 255));
        jlbReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbReset.setText("Reset");
        jlbReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbResetMouseReleased(evt);
            }
        });
        jPanel1.add(jlbReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 60, 40));

        lbDK.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbDK.setForeground(new java.awt.Color(255, 255, 255));
        lbDK.setText("ĐĂNG KÍ");
        lbDK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDKMouseClicked(evt);
            }
        });
        jPanel1.add(lbDK, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/depositphotos_50523105-stock-photo-pizza-with-tomatoes.jpg"))); // NOI18N
        jLabel1.setText(" ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTKActionPerformed

    private void jlbDNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbDNMouseClicked

    }//GEN-LAST:event_jlbDNMouseClicked


    
   
    private void jlbDNMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbDNMouseReleased
        String username = textTK.getText();
        String password = new String(textPW.getPassword());
        StringBuilder sb = new StringBuilder();
        if (username.equals("")) {
            sb.append("UserName is empty");
        }
        if (password.equals("")) {
            sb.append("Password is empty");
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Invalid", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            for (int i = 0; i < dnTK(username, password).size(); i++) {
                TAIKHOAN tk = dnTK(username, password).get(i);
                if (tk.getTEN_TAI_KHOAN().equalsIgnoreCase(username) && tk.getMAT_KHAU().equalsIgnoreCase(password)) {

                    JOptionPane.showMessageDialog(this, "đăng nhập thành công! ");

                    viewMain v = null;
                    try {
                        v = new viewMain();
                    } catch (SQLException ex) {
                        Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    v.setVisible(true);
                    this.setVisible(false);

                }
                else{
                    JOptionPane.showMessageDialog(this, sb.toString(), "ĐĂNG NHẬP THẤT BẠI !", JOptionPane.ERROR_MESSAGE);
                }
                

            }
            


    }       

    }//GEN-LAST:event_jlbDNMouseReleased
    
    private void jlbResetMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbResetMouseReleased
        textTK.setText("");
        textPW.setText("");
        textTK.requestFocus();
    }//GEN-LAST:event_jlbResetMouseReleased

    private void textTKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTKKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            textPW.requestFocus();
        }
    }//GEN-LAST:event_textTKKeyPressed

    private void textPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPWActionPerformed

    }//GEN-LAST:event_textPWActionPerformed

    private void lbDKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDKMouseClicked
        FormDangKi dk = new FormDangKi();
        this.setVisible(false);
        dk.setVisible(true);
    }//GEN-LAST:event_lbDKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcbGhiNho;
    private javax.swing.JLabel jlbDN;
    private javax.swing.JLabel jlbReset;
    private javax.swing.JLabel lbDK;
    private javax.swing.JPasswordField textPW;
    private javax.swing.JTextField textTK;
    // End of variables declaration//GEN-END:variables
}
