/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLyPizza.View;

import static QuanLyPizza.Connect.MyConnect.getConnection;
import static QuanLyPizza.DAO.TaiKhoanDAO.dkTK;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HUU77
 */
public class FormDangKi extends javax.swing.JFrame {

//    data dt = new data();

    public FormDangKi() {
        initComponents();
        setLocationRelativeTo(null);
        getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TXTMATK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pwDK = new javax.swing.JPasswordField();
        cfDK = new javax.swing.JTextField();
        taoTK = new javax.swing.JLabel();
        ĐN_NGAY = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tkDK1 = new javax.swing.JTextField();
        TXTMANV1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐĂNG KÍ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 160, 50));

        TXTMATK.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TXTMATK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTMATKKeyPressed(evt);
            }
        });
        jPanel1.add(TXTMATK, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONFIRM");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 90, -1));

        pwDK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwDKKeyPressed(evt);
            }
        });
        jPanel1.add(pwDK, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 180, -1));

        cfDK.setText(" ");
        cfDK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cfDKKeyPressed(evt);
            }
        });
        jPanel1.add(cfDK, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 180, -1));

        taoTK.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        taoTK.setForeground(new java.awt.Color(255, 255, 255));
        taoTK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taoTK.setText("TẠO TÀI KHOẢN");
        taoTK.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                taoTKAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        taoTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                taoTKMouseReleased(evt);
            }
        });
        jPanel1.add(taoTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 200, -1));

        ĐN_NGAY.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        ĐN_NGAY.setForeground(new java.awt.Color(255, 255, 255));
        ĐN_NGAY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ĐN_NGAY.setText("ĐĂNG NHẬP NGAY");
        ĐN_NGAY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ĐN_NGAYMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ĐN_NGAYMouseReleased(evt);
            }
        });
        jPanel1.add(ĐN_NGAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 220, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MÃ TÀI KHOẢN");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PASSWORD");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TAI KHOẢN");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, -1));

        tkDK1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tkDK1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tkDK1KeyPressed(evt);
            }
        });
        jPanel1.add(tkDK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 180, -1));

        TXTMANV1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TXTMANV1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTMANV1KeyPressed(evt);
            }
        });
        jPanel1.add(TXTMANV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 180, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("MÃ NHÂN VIÊN");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 110, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/DKimg.jpg"))); // NOI18N
        jLabel2.setText(" ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 550, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ĐN_NGAYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ĐN_NGAYMouseClicked

    }//GEN-LAST:event_ĐN_NGAYMouseClicked

    private void taoTKAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_taoTKAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_taoTKAncestorAdded

    private void taoTKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taoTKMouseReleased
        String username = tkDK1.getText();
        String password = new String(pwDK.getPassword());
        String confirm = cfDK.getText();
        String MATK = TXTMATK.getText();
        String MANV = TXTMANV1.getText();
        StringBuilder sb = new StringBuilder();
        if (username.equals("")) {
            sb.append("UserName is empty");
        }
          if (MANV.equals("")) {
            sb.append("MANV is empty");
        }
             if (MATK.equals("")) {
            sb.append("MANV is empty");
        }
        if (password.equals("")) {
            sb.append("Password is empty");
        }
        if (confirm.equals("") ) {
            sb.append("Confirm Password is empty");
        }
      
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Invalid", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            try {
                if (dkTK(MATK,username, password,MANV) != null) {
                    JOptionPane.showMessageDialog(this, "bạn đã dăng kí thành công! ");
                } else {
                    JOptionPane.showMessageDialog(this, sb.toString(), "ĐĂNG KÍ THẤT BẠI !", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(FormDangKi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_taoTKMouseReleased

    private void TXTMATKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTMATKKeyPressed
          if (evt.getKeyCode() == evt.VK_ENTER) {
            pwDK.requestFocus();
        }
    }//GEN-LAST:event_TXTMATKKeyPressed

    private void pwDKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwDKKeyPressed
         if (evt.getKeyCode() == evt.VK_ENTER) {
            cfDK.requestFocus();
        }
    }//GEN-LAST:event_pwDKKeyPressed

    private void cfDKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cfDKKeyPressed
      
    }//GEN-LAST:event_cfDKKeyPressed

    private void ĐN_NGAYMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ĐN_NGAYMouseReleased
        DangNhap dn=new DangNhap();
        this.setVisible(false);
        dn.setVisible(true);
    }//GEN-LAST:event_ĐN_NGAYMouseReleased

    private void tkDK1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tkDK1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkDK1KeyPressed

    private void TXTMANV1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTMANV1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTMANV1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDangKi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTMANV1;
    private javax.swing.JTextField TXTMATK;
    private javax.swing.JTextField cfDK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pwDK;
    private javax.swing.JLabel taoTK;
    private javax.swing.JTextField tkDK1;
    private javax.swing.JLabel ĐN_NGAY;
    // End of variables declaration//GEN-END:variables
}
