/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package QuanLyPizza.View;

import QuanLyPizza.Class.NHANVIEN;
import QuanLyPizza.Class.TAIKHOAN;
import static QuanLyPizza.DAO.TaiKhoanDAO.addTK;
import static QuanLyPizza.DAO.TaiKhoanDAO.deleteTK;
import static QuanLyPizza.DAO.TaiKhoanDAO.getAllTK;
import static QuanLyPizza.DAO.TaiKhoanDAO.searchTK;
import static QuanLyPizza.DAO.TaiKhoanDAO.updateTK;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.text.html.HTML.Tag.S;

/**
 *
 * @author HP
 */
public class FormTaiKhoan extends javax.swing.JDialog {

    /**
     * Creates new form FormTaiKhoan
     */
    String MaNV;
    public FormTaiKhoan(java.awt.Frame parent, boolean modal , String s) {
        super(parent, modal);
        initComponents();
        labelMaNV.setText(s);
        MaNV = s;
        showTK();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelMaNV = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldMaTK = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldLogin = new javax.swing.JTextField();
        fieldPassWord = new javax.swing.JTextField();
        btnSetUpTK = new javax.swing.JButton();
        btnDeleteTK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText("Mã NV");

        jLabel3.setText("Mã TK");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("THIẾT LẬP TÀI KHOẢN");

        jLabel5.setText("UserName");

        jLabel6.setText("PassWord");

        btnSetUpTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8_password_reset_32px.png"))); // NOI18N
        btnSetUpTK.setText("Thiết lập");
        btnSetUpTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetUpTKActionPerformed(evt);
            }
        });

        btnDeleteTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icons8_denied_32px.png"))); // NOI18N
        btnDeleteTK.setText("Xóa");
        btnDeleteTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelMaNV))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(fieldMaTK))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnSetUpTK)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(fieldPassWord))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(fieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(btnDeleteTK))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelMaNV)
                    .addComponent(jLabel5)
                    .addComponent(fieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldMaTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(fieldPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetUpTK)
                    .addComponent(btnDeleteTK))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void btnSetUpTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetUpTKActionPerformed
        try {
            // TODO add your handling code here:
            autoUpdateTK();
        } catch (SQLException ex) {
            Logger.getLogger(FormTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        getAllTK();
    }//GEN-LAST:event_btnSetUpTKActionPerformed

    private void btnDeleteTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTKActionPerformed
        // TODO add your handling code here:
        deleteTK(MaNV);
        showTK();
    }//GEN-LAST:event_btnDeleteTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String s = "  ";
                FormTaiKhoan dialog = new FormTaiKhoan(new javax.swing.JFrame(), true, s );
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    //hàm này dùng để thêm data vào danh sách
    public void addTKForForm() throws SQLException{
        TAIKHOAN sp = new TAIKHOAN();
        if(fieldMaTK.getText().trim().isEmpty() == false & existTK(fieldMaTK.getText()) == false){
            sp.setMaTK(fieldMaTK.getText());
            sp.setTEN_TAI_KHOAN(fieldLogin.getText());
            sp.setMAT_KHAU(fieldPassWord.getText());
            sp.setMaNV(MaNV);
            addTK(sp);
            JOptionPane.showMessageDialog(rootPane, "Thiết lập thành công", "  ", JOptionPane.INFORMATION_MESSAGE); 
            btnDeleteTK.setEnabled(true);
        
        }else{
            JOptionPane.showMessageDialog(rootPane, "Thiết lập thất bại", "  ", JOptionPane.INFORMATION_MESSAGE); 
            btnDeleteTK.setEnabled(false);
        }
        
    }
    
    //hàm này dùng để xem maSP có tồn tại hay là không
    public boolean existTK(String s){
        ArrayList<TAIKHOAN> listSP = (ArrayList<TAIKHOAN>) getAllTK(); 
        for(TAIKHOAN sp : listSP){
            if(sp.getMaTK().trim().equals(s.trim())){
                return true;
            }
        }
        return false;
    }
    
    
    
    //hàm này dùng để cập nhật lại sản phẩm
    public void updateTKForProduct(String s){
        TAIKHOAN sp = new TAIKHOAN();       
        if(existTK(fieldMaTK.getText()) == false || fieldMaTK.getText().trim().equals(s.trim())){
            sp.setMaTK(fieldMaTK.getText());
            sp.setTEN_TAI_KHOAN(fieldLogin.getText());
            sp.setMAT_KHAU(fieldPassWord.getText());
            updateTK(sp ,MaNV );
            JOptionPane.showMessageDialog(rootPane, "Thiết lập thành công", "  ", JOptionPane.INFORMATION_MESSAGE); 
            btnDeleteTK.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Thiết lập thất bại", "  ", JOptionPane.INFORMATION_MESSAGE); 
            btnDeleteTK.setEnabled(true);
        }
        
        
    }
  
 
    //hàm này dùng để xem maSP có tồn tại hay là không
    public boolean existNV_TK(String s){
        ArrayList<TAIKHOAN> listSP = (ArrayList<TAIKHOAN>) getAllTK(); 
        for(TAIKHOAN sp : listSP){
            if(sp.getMaNV().trim().equals(s.toLowerCase().trim())){
                return true;
            }
        }
        return false;
    }
    
    public void autoUpdateTK() throws SQLException{
        boolean key = existNV_TK(MaNV);
        if(key == false){
            addTKForForm();
        }else{
            TAIKHOAN tk = searchTK(MaNV);
            updateTKForProduct(tk.getMaTK());
        }
    }
    
    public void showTK(){
        TAIKHOAN sp = searchTK(MaNV);
        if(sp.getMaTK() == null){
            btnDeleteTK.setEnabled(false);
        }else{
            btnDeleteTK.setEnabled(true);
        }
        fieldMaTK.setText(sp.getMaTK());
        fieldLogin.setText(sp.getTEN_TAI_KHOAN());
        fieldPassWord.setText(sp.getMAT_KHAU());
    }
    
    

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteTK;
    private javax.swing.JButton btnSetUpTK;
    private javax.swing.JTextField fieldLogin;
    private javax.swing.JTextField fieldMaTK;
    private javax.swing.JTextField fieldPassWord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelMaNV;
    // End of variables declaration//GEN-END:variables
}
