/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLyPizza.View;

import QuanLyPizza.Class.HOADON;
import QuanLyPizza.Class.KHACHHANG;
import QuanLyPizza.Class.KHUYENMAI;
import QuanLyPizza.Class.SANPHAM;
import static QuanLyPizza.DAO.ChiTietHoaDonDAO.addCTHD;
import static QuanLyPizza.DAO.HoaDonDAO.addHD;
import static QuanLyPizza.DAO.HoaDonDAO.count_max;
import static QuanLyPizza.DAO.KhachHangDAO.AotuUpdateKH;
import static QuanLyPizza.DAO.KhachHangDAO.getAllKH;
import static QuanLyPizza.DAO.KhachHangDAO.getTKHKey;
import static QuanLyPizza.DAO.KhuyenMaiDAO.getAllKM;
import static QuanLyPizza.DAO.KhuyenMaiDAO.showCOMBOBOX_IN_HOA_DON;
import static QuanLyPizza.DAO.SanPhamDAO.getSLSPKey;
import static QuanLyPizza.DAO.SanPhamDAO.updateTBSP;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author HUU77
 */
public class InHoaDon extends javax.swing.JFrame {

    public List<SANPHAM> newLIST = new ArrayList<>();
    public String MaNV;

    private InHoaDon() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void setMaNV(String MaNV1) {
        this.MaNV = MaNV1;
    }

    //hàm get và hàm set
    public void setNewLIST(List<SANPHAM> newLIST) {
        this.newLIST = newLIST;

    }

    public List<SANPHAM> getNewLIST() {
        return newLIST;
    }

    /**
     * Creates new form IN_HOA_DON
     */
    public InHoaDon(List<SANPHAM> newLIST1) throws SQLException {
        initComponents();
        newLIST = newLIST1;
        showCOMBOBOX_IN_HOA_DON1();
        setLocationRelativeTo(null);
        btnIN_HOA_DON.setEnabled(false);
    }

    // dịnh dạng ngày
    public static final String DATE_FORMAT_NOW = "dd-MM-yyyy";

    //hàm lấy ngày hiện tại
    public static String ngayH() {
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT_NOW);
        return sdf.format(cal.getTime());
    }

    //show dư liệu lên combobox 
    public void showCOMBOBOX_IN_HOA_DON1() throws SQLException {
        List<KHUYENMAI> list = getAllKM();
        for (KHUYENMAI d : list) {
//            System.out.println(d.getDieuKienKM() + "                lsdmflkmsdflmsad;fm;alsm");
//            System.out.println(TongTien() + "                       tổng tiền");
            if (TongTien() >= d.getDieuKienKM()) {
                comboboxIHD.addItem(d.getMaKM());
            }

        }
    }

    //hàm này để tính tổng tiền
    public void handleDuLieu() throws SQLException {
        double sum = 0;
        for (int i = 0; i < newLIST.size(); i++) {
            SANPHAM sp = (SANPHAM) newLIST.get(i);
            sum += (sp.getGia() * sp.getSoLuongConLai());
        }
        txttongtien.setText(String.valueOf(sum));
    }

    //hàm này tính tổng tiền để xử lý ở combobox
    public double TongTien() throws SQLException {
        double sum = 0;
        for (int i = 0; i < newLIST.size(); i++) {
            SANPHAM sp = (SANPHAM) newLIST.get(i);
            sum += (sp.getGia() * sp.getSoLuongConLai());
        }
        return sum;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFormMainIHD = new javax.swing.JTextArea();
        btnIN_HOA_DON = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKhCTHD = new javax.swing.JTextField();
        txttongtien = new javax.swing.JTextField();
        comboboxIHD = new javax.swing.JComboBox<>();
        btnXEMTRUOC = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        MaKHForHD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHI TIẾT HÓA ĐƠN ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 27, 476, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, -1));

        txtFormMainIHD.setColumns(20);
        txtFormMainIHD.setRows(5);
        jScrollPane1.setViewportView(txtFormMainIHD);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
        );

        btnIN_HOA_DON.setText("IN HÓA ĐƠN");
        btnIN_HOA_DON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIN_HOA_DONActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("KHÁCH HÀNG");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("TỔNG TIỀN ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("MÃ GIẢM");

        txtKhCTHD.setText(" ");

        txttongtien.setText(" ");
        txttongtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttongtienActionPerformed(evt);
            }
        });

        comboboxIHD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NULL" }));
        comboboxIHD.setName(""); // NOI18N
        comboboxIHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboboxIHDMouseClicked(evt);
            }
        });
        comboboxIHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxIHDActionPerformed(evt);
            }
        });

        btnXEMTRUOC.setText("XEM TRUOC");
        btnXEMTRUOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXEMTRUOCActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("MÃ KH");

        MaKHForHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaKHForHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXEMTRUOC)
                .addGap(183, 183, 183)
                .addComponent(btnIN_HOA_DON)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txttongtien, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(txtKhCTHD)
                    .addComponent(comboboxIHD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MaKHForHD))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addComponent(txtKhCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(MaKHForHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboboxIHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIN_HOA_DON)
                    .addComponent(btnXEMTRUOC))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String phantram = "";

    private void btnIN_HOA_DONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIN_HOA_DONActionPerformed
        // TODO add your handling code here:
        btnIN_HOA_DON.setEnabled(false);
        checkKHGia();
        // xuất ra file pdf
        String filePath;
        filePath = "C:\\Users\\HP\\Documents\\NetBeansProjects\\DOAN-1\\DOAN-1\\src\\QuanLyPizza\\HoaDon\\hoadon.txt";
        System.out.println(filePath);
        handleIN_HOA_DON(filePath);
        JOptionPane.showMessageDialog(this, "IN HÓA ĐƠN THÀNH CÔNG! ");
        //dùng để chèn vào bảng hóa đơn
        HOADON hd = new HOADON();
        hd.setMaHD("hd" + String.valueOf(count_max()));
        hd.setTen(MaNV);
        hd.setThanhTien(Double.parseDouble(txttongtien.getText()));
        Date date = new Date();
        hd.setNgaylap(date);
        String makm = (String) comboboxIHD.getSelectedItem();
        addHD(hd, makm);
        //chèn vào chi tiết hóa đơn   
        int soluong = 0;
        double tongCT = 0;
        for (SANPHAM sp : newLIST) {
            tongCT = tongCT + sp.getSoLuongConLai() * sp.getGia();
            addCTHD(sp, hd.getMaHD(), MaKHForHD.getText());
            soluong = getSLSPKey(sp.getMaSP()) - sp.getSoLuongConLai();
            updateTBSP(String.valueOf(soluong), sp.getMaSP());
        }
        if (MaKHForHD.getText().trim().length() != 0) {
            AotuUpdateKH(getTKHKey(MaKHForHD.getText().trim()) + tongCT, MaKHForHD.getText().trim());
        }


    }//GEN-LAST:event_btnIN_HOA_DONActionPerformed

    public static String tenKH = "";

    public boolean existKH(String s) {
        tenKH = "";
        ArrayList<KHACHHANG> listKH = (ArrayList<KHACHHANG>) getAllKH();
        for (KHACHHANG kh : listKH) {
            if (kh.getMaKH().trim().equals(s.toLowerCase().trim())) {
                tenKH = kh.getTenKH();
                return true;
            }
        }
        return false;
    }

    public void checkKH() {
        if (existKH(MaKHForHD.getText().trim())) {
            txtKhCTHD.setText(tenKH);
        }

    }

    //hàm này dùng để lấy giá
    public void checkKHGia() {
        // TODO add your handling code here:
        String x = (String) comboboxIHD.getSelectedItem();
        System.out.println(x);
        if (x.trim().equals("NULL")) {
            phantram = String.valueOf("0");
            System.out.println(phantram);
        } else {
            List<KHUYENMAI> list = getAllKM();
            for (KHUYENMAI d : list) {
                if (x.trim().equals(d.getMaKM().trim())) {
                    phantram = String.valueOf(d.getPhanTramKM());
                }
            }
        }

    }

    public static String tenSP = "";
    public static String t = "";

    private void btnXEMTRUOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXEMTRUOCActionPerformed
        //hàm này xem mã khách hàng có tồn tại hay ko
        btnIN_HOA_DON.setEnabled(true);
        checkKHGia();

        // TODO add your handling code here:
        if (txtKhCTHD.getText().equalsIgnoreCase(" ")) {
            JOptionPane.showMessageDialog(this, "LỖI", "TÊN KHÁCH HÀNG KHÔNG ĐUCOWJ ĐỂ TRỐNG !", JOptionPane.ERROR_MESSAGE);
        } else {
            try {

                handleDuLieu();
            } catch (SQLException ex) {
                Logger.getLogger(InHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            }

//XỬ LÍ ĐƯA TÊN ,SỐ LUONG,GIÁ  VÀ TIỀN RA STRING T
            Double a = Double.parseDouble(txttongtien.getText()) * Double.parseDouble(phantram) * 0.01;
            String tienDaKhuyenMai = String.valueOf(Double.parseDouble(txttongtien.getText()) - a);
            for (int i = 0; i < newLIST.size(); i++) {
                SANPHAM sp = (SANPHAM) newLIST.get(i);
                System.out.println(sp.getMaSP() + "     " + sp.getTen_SP() + "     " + sp.getMaLoai() + "      maihaisjdfkjsdf");
                tenSP += sp.getName() + "                                 " + String.valueOf(sp.getSoLuongConLai()) + "                       " + String.valueOf(sp.getGia()) + "           " + String.valueOf((sp.getSoLuongConLai() * sp.getGia())) + "\n";
            }

            t = "                                                                                                   \n"
                    + "                                            CỬA HÀNG PIZZA NHÀ IT \n"
                    + "                                                                                                   \n"
                    + "                                    65/13H đường số 2 tăng nhơn phú A quận 9\n"
                    + "                                                                                                   \n"
                    + "------------------------------------------------------------------------------------------------\n"
                    + "                                            HÓA ĐƠN THANHH TOÁN\n"
                    + "                                                                                                   \n"
                    + "NGÀY THANH TOAN:                  " + this.ngayH() + "\n"
                    + "NHÂN VIÊN THANH TOÁN:        " + MaNV + "       "
                    + "TÊN KHÁCH HÀNG :                     " + txtKhCTHD.getText() + "\n"
                    + "------------------------------------------------------------------------------------------------\n"
                    + "                                                                                                   \n"
                    + "TÊN SẢN PHÂM                    SỐ LƯỢNG               GIÁ               THÀNH TIỀN      \n"
                    + tenSP + "\n"
                    + "------------------------------------------------------------------------------------------------\n"
                    + "                                                                                                   \n"
                    + " TỔNG TIỀN :                                                                    " + txttongtien.getText() + " VN DONG\n"
                    + " MÃ GIẢM GIÁ :                                                                    " + phantram + " %\n"
                    + "------------------------------------------------------------------------------------------------\n"
                    + "------------------------------------------------------------------------------------------------\n"
                    + "                                                                                  " + tienDaKhuyenMai + "\n";

            txtFormMainIHD.setText(t);
            System.out.println(t);
            btnXEMTRUOC.setEnabled(false);
        }

    }//GEN-LAST:event_btnXEMTRUOCActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setVisible(false);
        tenSP = "";
    }//GEN-LAST:event_jLabel6MouseClicked

    private void txttongtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttongtienActionPerformed
        // TODO add your handling code here:
        try {
            handleDuLieu();
        } catch (SQLException ex) {
            Logger.getLogger(InHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txttongtienActionPerformed

    private void comboboxIHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxIHDActionPerformed


    }//GEN-LAST:event_comboboxIHDActionPerformed

    private void MaKHForHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaKHForHDActionPerformed
        // TODO add your handling code here:
        checkKH();
    }//GEN-LAST:event_MaKHForHDActionPerformed

    private void comboboxIHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboboxIHDMouseClicked
        try {
            // TODO add your handling code here:
            showCOMBOBOX_IN_HOA_DON1();
        } catch (SQLException ex) {
            Logger.getLogger(InHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboboxIHDMouseClicked

    //hàm này dùng để xuất hóa đơn
    public static void handleIN_HOA_DON(String filepath) {
        try {

            PrintWriter pw = new PrintWriter(filepath, "UTF-8");
            pw.println(t);
            pw.flush();
            pw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MaKHForHD;
    private javax.swing.JButton btnIN_HOA_DON;
    private javax.swing.JButton btnXEMTRUOC;
    private javax.swing.JComboBox<String> comboboxIHD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtFormMainIHD;
    private javax.swing.JTextField txtKhCTHD;
    private javax.swing.JTextField txttongtien;
    // End of variables declaration//GEN-END:variables
}
